name: Release Workflow
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
    secrets:
      ATTICUS_PAT:
        required: true


jobs:
  semantic-release:
    name: Semantic Release and Publish
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/pygizmokit/
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # needed for GitHub actions bot to write to repo
#    needs: tests
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event.pull_request.merged == true)
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ATTICUS_PAT }}
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Pull latest changes
        run: git pull origin main

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.ATTICUS_PAT }}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11
        # NOTE: DO NOT wrap the conditional in ${{ }} as  evaluate to true.
        if: steps.release.outputs.released == 'true'

      - name: Publish package distributions to GitHub Releases
        uses: python-semantic-release/upload-to-gh-release@main
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.ATTICUS_PAT }}
